services:
  dvwa:
    build:
      context: ./dvwa
    container_name: victim-dvwa
    ports:
      - "8080:80"
    environment:
      - DB_SERVER=127.0.0.1
      - DB_DATABASE=dvwa
      - DB_USER=dvwa
      - DB_PASSWORD=dvwa
      - DB_PORT=3306
      - DEFAULT_SECURITY_LEVEL=low
      - DISABLE_AUTHENTICATION=false
    volumes:
      - dvwa-logs:/var/log/apache2
      - dvwa-internal-db-data:/var/lib/mysql
    networks:
      - victim-net

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.12.0
    container_name: filebeat-shipper
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - dvwa-logs:/var/log/dvwa:ro        # DVWA Apache 로그 연결
    depends_on:
      - dvwa
    networks:
      - victim-net
      - elk

volumes:
  dvwa-logs:
  dvwa-internal-db-data:

networks:
  victim-net:
    driver: bridge
  elk:
    external: true
    name: elk-stack
