filebeat.inputs:
  # DVWA Apache 웹 접속 로그
  - type: log
    enabled: true
    paths:
      - /var/log/dvwa/access.log
      - /var/log/dvwa/error.log
    fields:
      service: dvwa-apache

output.logstash:
  hosts: [ "logstash:5044" ]

# Filebeat 내부 로그 수준 설정
logging.level: info
